// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package simulator

import "strconv"

type Method int16

const (
	MethodGET    Method = 0
	MethodPOST   Method = 1
	MethodPATCH  Method = 2
	MethodDELETE Method = 3
)

var EnumNamesMethod = map[Method]string{
	MethodGET:    "GET",
	MethodPOST:   "POST",
	MethodPATCH:  "PATCH",
	MethodDELETE: "DELETE",
}

var EnumValuesMethod = map[string]Method{
	"GET":    MethodGET,
	"POST":   MethodPOST,
	"PATCH":  MethodPATCH,
	"DELETE": MethodDELETE,
}

func (v Method) String() string {
	if s, ok := EnumNamesMethod[v]; ok {
		return s
	}
	return "Method(" + strconv.FormatInt(int64(v), 10) + ")"
}
